### ISSUE TITLE
Relay no longer works

### ISSUE THREAD

**Issue by Fmstrat** [eggbean/docker-weechat#5]
When running weechat in relay mode after the latest round of updates, weechat no longer listens on the relay port. Since the tags on docker HUB are all using latest (and no version numbers), I can't tell where the breaking change took place. I do know things work in `eggbean/weechat@sha256:9989b98e204fc1a6951f1a6497e5c54f8740be10b06194c574eea8944ba9fa59` but not in `eggbean/weechat:latest`

**Comment by Fmstrat** [comment]
Nope, that didn't do it

**Comment by eggbean** [comment]
Hi, sorry for the delay. I get a lot of plugin errors on the startup screen. I will look into it now. Now that there are no previous builds available on the docker hub free accounts, it's making it a lot harder for me to figure out what's going on.

**Comment by Fmstrat** [comment]
Oh np, just running the old version for now. I'm about to modify my personal build scripts to push YYYYMMDD images in addition to latest for exactly that reason. Luckily docker hub still has the images you can pull, they're just not listed.

**Comment by eggbean** [comment]
If you're still using this container, I finally found the problem! My mistake was relying on the official project Dockerfile for checking for dependencies, which has turned out to be out-of-date.

The x86_64 image is up on Docker Hub but I still need to get the armv7l and aarch64 builds working, so the image may change but with nothing changed in reality.
